'use client';
import Head from 'next/head';

import { Header, Footer } from '@/components/Ui';
import { LandingContainer } from '@/components/Landing';

const Landing = () => {
    return (
        <>
            <Head>
                <title>Nimble</title>
                <meta
                    name="description"
                    content="Generated by create next app"
                />
                <meta
                    name="viewport"
                    content="width=device-width, initial-scale=1"
                />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <main>
                <Header />
                <LandingContainer />
                <Footer />
            </main>
        </>
    );
};

export default Landing;
