import Head from 'next/head';

import Header from '@/components/Header';
import Footer from '@/components/Footer';
import Landing from '@/layouts/Landing';

export default function Home() {
    return (
        <>
            <Head>
                <title>Nimble</title>
                <meta
                    name="description"
                    content="Generated by create next app"
                />
                <meta
                    name="viewport"
                    content="width=device-width, initial-scale=1"
                />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <main>
                <Header />
                <Landing />
                <Footer />
            </main>
        </>
    );
}
